[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_sqlite", "php82Extensions.sqlite3", "php82Extensions.mbstring", "php82Extensions.openssl", "php82Extensions.tokenizer", "php82Extensions.xml", "php82Extensions.ctype", "php82Extensions.json", "composer"]
 
[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan route:cache",
  "php artisan view:cache"
]
 
[start]
cmd = "touch database/database.sqlite && php artisan migrate --seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"